- name: Hello World
  hosts: local
  connection: local
  tasks:
  - name: print the text
    ansible.builtin.debug:
     msg: "Hello World"

- name: this is second play book
  hosts: local
  connection: local
  tasks:
  - name: print the msg from playbook2
    ansible.builtin.debug:
      msg: "{{ 'This the msg from playbook 2'  }}"
     

