- name: ansible shell vs ansible command modules
  hosts: local
  connection: local
  tasks:
  - name: running command using ansible shell
    ansible.builtin.shell: cat /etc/passwd | grep root
    register: user_output 

  - name: Print the usersoutput
    ansible.builtin.debug:
      msg: "{{ user_output }}" 