- name: Demo on filters
  hosts: local
  connection: local
  vars:
    topics: linux, shell, ansible
    tag_list: 
        Course1: linux,
        Course2: shell,
        Course3: ansible
    tag_map:
      [
        {
            "key": "Course1",
            "value": "linux,"
        },
        {
            "key": "Course2",
            "value": "shell,"
        },
        {
            "key": "Course3",
            "value": "ansible"
        }
      ]

  tasks:
  - name: Convert string to list
    ansible.builtin.debug:
      msg: "{{ topics | split(',') }}"

  - name: convert list to map
    ansible.builtin.debug:
      msg: "{{ tag_list | dict2items }}"

  - name: convert map to list
    ansible.builtin.debug:
      msg: "{{ tag_map | items2dict }}"
