[frontend]
196.12.13.1
196.12.13.2
196.12.13.3

[backend]
196.12.13.4
196.12.13.5
196.12.13.6

[web]
172.31.12.154

[roboshop:children]
frontend
backend

[local]
localhost

[local:vars]
COURSE=ANisible from Inventory
NAME=Niteesh Gandham from inventory level
